name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install boost
      run: sudo apt-get update && sudo apt-get install -y libboost-dev

    - name: deps
      run: make deps

    - name: build
      run: make

    - name: test
      run: make test
